version: "3"

services:
  rasa:
    image: rasa/rasa:3.0.4-full
    ports:
      - 5005:5005
    networks:
      - production
    depends_on:
      - actions
    volumes:
      - ./bot/:/app
    command:
      - run 
      - --enable-api
      - --cors
      - "*"

  actions:
    build:
      context: ./dockers
      dockerfile: web.Dockerfile
    ports:
      - 5055:5055
    networks:
      - production

  web:
    build:
      context: ./dockers
      dockerfile: web.Dockerfile
    image: web
    container_name: web
    ports:
      - 8080:8080
    networks:
      - production
    depends_on:
      - rasa
      - actions


networks: 
    production:
        driver: bridge